//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/04.InputActions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""76f4f64a-9d9a-49db-a311-5763122125a8"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""361ef868-2235-4a74-9369-af77c6d4c37a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""b7fec758-d0f7-4022-8311-58066fcd1f23"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""517e01ed-64ee-4d77-a901-ae43c66943b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f6141d88-5cd4-479a-80af-96fba32a7412"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""42cf4f40-d34d-4519-8d27-d152f872100f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": "" Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""959b7a8d-13c7-4b32-a8d7-6434de3ba144"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar1"",
                    ""type"": ""Button"",
                    ""id"": ""69835c4c-c6bd-4d57-8838-bc6f7e484fdb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar2"",
                    ""type"": ""Button"",
                    ""id"": ""716b5746-54a9-490e-9386-9eed06f9ee27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar3"",
                    ""type"": ""Button"",
                    ""id"": ""324985da-7445-4064-949c-bd47dda0d548"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar4"",
                    ""type"": ""Button"",
                    ""id"": ""986af48d-68ab-4cf9-b7ee-e25ad931acac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar5"",
                    ""type"": ""Button"",
                    ""id"": ""79c6fd27-8fa9-4af2-9e95-ee28b410dc05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar6"",
                    ""type"": ""Button"",
                    ""id"": ""b904d102-8d01-4791-8255-149a90597fcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar7"",
                    ""type"": ""Button"",
                    ""id"": ""76434043-df58-40f2-8b00-4fd317f8af62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar8"",
                    ""type"": ""Button"",
                    ""id"": ""543b81f6-9c25-4908-bd90-f7735155924c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HotBar9"",
                    ""type"": ""Button"",
                    ""id"": ""0fac0cf2-47bc-4f56-a597-4659dbbfb2c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""1547e169-429c-4c55-b17b-596142e62cca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""c96620e1-a851-47b7-a1bb-75affc40c41f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""314b3ed0-c656-4022-b115-541c7203703f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""240fba37-9ac1-43e0-bf2e-b6a0bab40eb9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ba8f3b4e-eebb-4647-acac-9c525940b9af"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""38263577-3529-484e-955d-92b28c7d0cdc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""390bbc35-bd84-44e7-a3f8-c26ca421e71a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6ddea5f3-2735-4baf-a347-1496345c9717"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""89694da5-8acc-45f4-82d8-6c4dbc2340b6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cfce6d1-bc1c-40af-b936-6ae751063f6f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4ab96b1-f60b-4e85-a19b-9c7b94f43db9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4302c7e6-7738-4010-8e69-3909f92820b5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfb20a87-3702-478a-a0d0-4fea35d283b9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd4938e5-d905-4e4e-9870-b144f077413f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""301280bd-eeb4-4a17-801a-208e669b625c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29ce520c-f649-4d64-b70e-89c462d7d3fd"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""100029f4-bc95-408b-9b75-f5ecc86df9b9"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e0576d7-6683-4126-87a2-dc79a8d0b18a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1723996-20ff-409b-b201-b8bca9bbb180"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f536ba8-08c6-4572-b82f-19e9f9e83eec"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25743825-3241-4c19-9882-8b40eef526e0"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""843c7fd4-e2fe-48c9-b0f3-b025f4fe68a9"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""258e1814-1d9e-4a9c-9ee7-6068399d77a1"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7abcf7b3-d026-4e2c-adae-bd8d09415461"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5152c74-a592-4dae-a305-071bfb39dd07"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": "" Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Interaction = m_Player.FindAction(" Interaction", throwIfNotFound: true);
        m_Player_HotBar1 = m_Player.FindAction("HotBar1", throwIfNotFound: true);
        m_Player_HotBar2 = m_Player.FindAction("HotBar2", throwIfNotFound: true);
        m_Player_HotBar3 = m_Player.FindAction("HotBar3", throwIfNotFound: true);
        m_Player_HotBar4 = m_Player.FindAction("HotBar4", throwIfNotFound: true);
        m_Player_HotBar5 = m_Player.FindAction("HotBar5", throwIfNotFound: true);
        m_Player_HotBar6 = m_Player.FindAction("HotBar6", throwIfNotFound: true);
        m_Player_HotBar7 = m_Player.FindAction("HotBar7", throwIfNotFound: true);
        m_Player_HotBar8 = m_Player.FindAction("HotBar8", throwIfNotFound: true);
        m_Player_HotBar9 = m_Player.FindAction("HotBar9", throwIfNotFound: true);
        m_Player_Use = m_Player.FindAction("Use", throwIfNotFound: true);
        m_Player_Drop = m_Player.FindAction("Drop", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Interaction;
    private readonly InputAction m_Player_HotBar1;
    private readonly InputAction m_Player_HotBar2;
    private readonly InputAction m_Player_HotBar3;
    private readonly InputAction m_Player_HotBar4;
    private readonly InputAction m_Player_HotBar5;
    private readonly InputAction m_Player_HotBar6;
    private readonly InputAction m_Player_HotBar7;
    private readonly InputAction m_Player_HotBar8;
    private readonly InputAction m_Player_HotBar9;
    private readonly InputAction m_Player_Use;
    private readonly InputAction m_Player_Drop;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Interaction => m_Wrapper.m_Player_Interaction;
        public InputAction @HotBar1 => m_Wrapper.m_Player_HotBar1;
        public InputAction @HotBar2 => m_Wrapper.m_Player_HotBar2;
        public InputAction @HotBar3 => m_Wrapper.m_Player_HotBar3;
        public InputAction @HotBar4 => m_Wrapper.m_Player_HotBar4;
        public InputAction @HotBar5 => m_Wrapper.m_Player_HotBar5;
        public InputAction @HotBar6 => m_Wrapper.m_Player_HotBar6;
        public InputAction @HotBar7 => m_Wrapper.m_Player_HotBar7;
        public InputAction @HotBar8 => m_Wrapper.m_Player_HotBar8;
        public InputAction @HotBar9 => m_Wrapper.m_Player_HotBar9;
        public InputAction @Use => m_Wrapper.m_Player_Use;
        public InputAction @Drop => m_Wrapper.m_Player_Drop;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @HotBar1.started += instance.OnHotBar1;
            @HotBar1.performed += instance.OnHotBar1;
            @HotBar1.canceled += instance.OnHotBar1;
            @HotBar2.started += instance.OnHotBar2;
            @HotBar2.performed += instance.OnHotBar2;
            @HotBar2.canceled += instance.OnHotBar2;
            @HotBar3.started += instance.OnHotBar3;
            @HotBar3.performed += instance.OnHotBar3;
            @HotBar3.canceled += instance.OnHotBar3;
            @HotBar4.started += instance.OnHotBar4;
            @HotBar4.performed += instance.OnHotBar4;
            @HotBar4.canceled += instance.OnHotBar4;
            @HotBar5.started += instance.OnHotBar5;
            @HotBar5.performed += instance.OnHotBar5;
            @HotBar5.canceled += instance.OnHotBar5;
            @HotBar6.started += instance.OnHotBar6;
            @HotBar6.performed += instance.OnHotBar6;
            @HotBar6.canceled += instance.OnHotBar6;
            @HotBar7.started += instance.OnHotBar7;
            @HotBar7.performed += instance.OnHotBar7;
            @HotBar7.canceled += instance.OnHotBar7;
            @HotBar8.started += instance.OnHotBar8;
            @HotBar8.performed += instance.OnHotBar8;
            @HotBar8.canceled += instance.OnHotBar8;
            @HotBar9.started += instance.OnHotBar9;
            @HotBar9.performed += instance.OnHotBar9;
            @HotBar9.canceled += instance.OnHotBar9;
            @Use.started += instance.OnUse;
            @Use.performed += instance.OnUse;
            @Use.canceled += instance.OnUse;
            @Drop.started += instance.OnDrop;
            @Drop.performed += instance.OnDrop;
            @Drop.canceled += instance.OnDrop;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @HotBar1.started -= instance.OnHotBar1;
            @HotBar1.performed -= instance.OnHotBar1;
            @HotBar1.canceled -= instance.OnHotBar1;
            @HotBar2.started -= instance.OnHotBar2;
            @HotBar2.performed -= instance.OnHotBar2;
            @HotBar2.canceled -= instance.OnHotBar2;
            @HotBar3.started -= instance.OnHotBar3;
            @HotBar3.performed -= instance.OnHotBar3;
            @HotBar3.canceled -= instance.OnHotBar3;
            @HotBar4.started -= instance.OnHotBar4;
            @HotBar4.performed -= instance.OnHotBar4;
            @HotBar4.canceled -= instance.OnHotBar4;
            @HotBar5.started -= instance.OnHotBar5;
            @HotBar5.performed -= instance.OnHotBar5;
            @HotBar5.canceled -= instance.OnHotBar5;
            @HotBar6.started -= instance.OnHotBar6;
            @HotBar6.performed -= instance.OnHotBar6;
            @HotBar6.canceled -= instance.OnHotBar6;
            @HotBar7.started -= instance.OnHotBar7;
            @HotBar7.performed -= instance.OnHotBar7;
            @HotBar7.canceled -= instance.OnHotBar7;
            @HotBar8.started -= instance.OnHotBar8;
            @HotBar8.performed -= instance.OnHotBar8;
            @HotBar8.canceled -= instance.OnHotBar8;
            @HotBar9.started -= instance.OnHotBar9;
            @HotBar9.performed -= instance.OnHotBar9;
            @HotBar9.canceled -= instance.OnHotBar9;
            @Use.started -= instance.OnUse;
            @Use.performed -= instance.OnUse;
            @Use.canceled -= instance.OnUse;
            @Drop.started -= instance.OnDrop;
            @Drop.performed -= instance.OnDrop;
            @Drop.canceled -= instance.OnDrop;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnHotBar1(InputAction.CallbackContext context);
        void OnHotBar2(InputAction.CallbackContext context);
        void OnHotBar3(InputAction.CallbackContext context);
        void OnHotBar4(InputAction.CallbackContext context);
        void OnHotBar5(InputAction.CallbackContext context);
        void OnHotBar6(InputAction.CallbackContext context);
        void OnHotBar7(InputAction.CallbackContext context);
        void OnHotBar8(InputAction.CallbackContext context);
        void OnHotBar9(InputAction.CallbackContext context);
        void OnUse(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
    }
}
